### ISSUE TITLE
/boot files are not used during the RPi first boot

### ISSUE THREAD

**Issue by ruzickap** [dtcooper/rpi-image-modifier#1]
Hello

It seems like the files like `/boot/userconf.txt` or `/boot/ssh` are not being used during the RPi first boot.

For example:

```yml
jobs:
  rpi-image-modifier:
    runs-on: ubuntu-latest
    steps:
      - name: Change Raspberry Pi OS
        uses: dtcooper/rpi-image-modifier@a72db974c3ef4068e79af05e86420a40c49f393f # v1.0.1
        id: create-image
        with:
          base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz
          image-path: 2024-03-15-raspios-bookworm-arm64-lite-modified.img
          run: |
            set -euxo pipefail

            touch /boot/ssh
            echo "pi:$y$j9T$teBQF20fiZEV5K3NZbwZ30$kIlVP6po2p43KH17C/26cmDN1i./cQriWj9Wp4rSHq2" > /boot/userconf.txt
```

The RPi image is correctly created but the ssh is not running after first boot + you need to manually create the "user" (headless installation is broken).

Thanks...
